services:
  devcontainer:
    image: python:3.11
    volumes:
      - ../:/backend

    command: sleep infinity

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fuckmongo
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: